Name:           ros-melodic-qpoases-vendor
Version:        3.2.0
Release:        2%{?dist}
Summary:        ROS qpoases_vendor package

Group:          Development/Libraries
License:        Apache License 2.0
URL:            https://projects.coin-or.org/qpOASES
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  ros-melodic-catkin

%description
Wrapper around qpOASES to make it available to the ROS ecosystem.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Thu Sep 12 2019 Geoffrey Biggs <geoff.biggs@tier4.jp> - 3.2.0-2
- Autogenerated by Bloom

* Tue Sep 10 2019 Geoffrey Biggs <geoff.biggs@tier4.jp> - 3.2.0-1
- Autogenerated by Bloom

